# Generated by Django 2.2.4 on 2019-12-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='softinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softname', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=32)),
                ('dir', models.CharField(max_length=256)),
                ('introduce', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
