# Generated by Django 2.2.4 on 2019-12-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=1024)),
                ('note', models.CharField(max_length=128)),
                ('siteroot', models.CharField(max_length=128)),
                ('ftp', models.CharField(max_length=128)),
                ('ftppass', models.CharField(max_length=128)),
                ('mysql', models.CharField(max_length=64)),
                ('mysqlpass', models.CharField(max_length=64)),
                ('sitephpver', models.CharField(max_length=16)),
                ('sitetag', models.CharField(max_length=16)),
            ],
        ),
    ]
