# Generated by Django 2.2.4 on 2020-01-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_siteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitetag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitetag', models.CharField(max_length=32)),
            ],
        ),
    ]
