# Generated by Django 2.1 on 2020-05-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_sitetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='domaininfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256)),
            ],
        ),
    ]
